# Generated by Django 4.1 on 2022-08-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('water_ammount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
