# Generated by Django 4.1 on 2022-08-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('light', models.CharField(max_length=200)),
                ('water', models.CharField(max_length=200)),
                ('humidity', models.CharField(max_length=200)),
                ('soil', models.CharField(max_length=200)),
                ('fertilizer', models.CharField(max_length=200)),
                ('toxcicity', models.BooleanField()),
                ('notes', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
